//! Example use of the `chart` crate: a door lock opened by a four-digit code.
//!
//!     cargo run --example door_lock
//!
//! Four states (Locked/Unlocked/Alarm/Maintenance) and seven edges.
//!
//! # Which vocabulary an effect belongs to
//!
//! Everything mutable lives in `Env`, and every write to it is an action. Where
//! the value comes from decides which kind: `attempts` comes from the state, so
//! `ResetAttempts` is a `StateAction` on `Locked`'s entry; `unlock_code` comes
//! from the event, so `Unlock` is an `Action` on the `UNLOCK` edge and only the
//! clearing is left to `Unlocked`'s exit.

use chart::machine::{Cond, Edge, Goto, Ignore, Machine, OnUnknown, Source, State};
use chart::{Domain, MachineSpec, render, verify};

chart::tags! {
    enum Tag {
        Locked,
        Unlocked,
        Alarm,
        Maintenance,
    }
}

// Event, Kind, HasKind and the coverage value list all come from this one
// declaration.
chart::events! {
    #[derive(Clone, Debug)]
    enum Event => Kind {
        EnterCode(u32),
        Timeout,
        Reset,
        MaintenanceToggle,
    }
}

/// Effects produced in reaction to an event. Only these can read `ev`.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
enum Action {
    Unlock,
    Beep,
    IncrementAttempts,
}

/// Effects of being in a state, run whichever edge led there.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
enum StateAction {
    ClearUnlockCode,
    Lock,
    ResetAttempts,
    SoundAlarm,
    MaintenanceOn,
    MaintenanceOff,
}

/// The outside world.
struct Env {
    correct_code: u32,
    attempts: u32,
    max_attempts: u32,
    /// Set by the `UNLOCK` edge and cleared by `Unlocked`'s exit action, so it is
    /// only meaningful while the door is unlocked.
    unlock_code: u32,
}

struct Door;

impl Domain for Door {
    type Event = Event;
    type EventKind = Kind;
    type Action = Action;
    type StateAction = StateAction;
    type Env = Env;

    fn perform(action: Action, ev: &Event, world: &mut Env) {
        match action {
            Action::Unlock => {
                if let Event::EnterCode(code) = ev {
                    world.unlock_code = *code;
                }
                println!("  [action] unlock (code {})", world.unlock_code);
            }
            Action::Beep => println!("  [action] beep (wrong code)"),
            Action::IncrementAttempts => {
                world.attempts += 1;
                println!("  [action] attempts = {}", world.attempts);
            }
        }
    }

    fn perform_state(action: StateAction, world: &mut Env) {
        match action {
            StateAction::ClearUnlockCode => world.unlock_code = 0,
            StateAction::Lock => println!("  [action] lock"),
            StateAction::ResetAttempts => {
                world.attempts = 0;
                println!("  [action] attempts reset");
            }
            StateAction::SoundAlarm => println!("  [action] alarm on"),
            StateAction::MaintenanceOn => println!("  [action] maintenance mode on"),
            StateAction::MaintenanceOff => println!("  [action] maintenance mode off"),
        }
    }

    // all_tags and all_kinds use their defaults, which read the Enumerable impls
    // generated by tags!/events!.
}

impl MachineSpec for Door {
    type Domain = Door;
    type Tag = Tag;
}

chart::cond_node!(Door, CodeCorrect, |cx| match cx.event {
    Event::EnterCode(code) => Cond::from(*code == cx.world.correct_code),
    _ => Cond::False,
});

chart::cond_node!(Door, AttemptsExceeded, |cx| Cond::from(
    cx.world.attempts >= cx.world.max_attempts
));

// `Unlock` reads the payload out of `ev`, so it sits on the `UNLOCK` edge;
// `ClearUnlockCode` needs no event and drops the code again on the way out.
static STATES: &[State<Door>] = &[
    State {
        tag: Tag::Locked,
        entry: &[StateAction::Lock, StateAction::ResetAttempts],
        exit: &[],
    },
    State {
        tag: Tag::Unlocked,
        entry: &[],
        exit: &[StateAction::ClearUnlockCode],
    },
    State {
        tag: Tag::Alarm,
        entry: &[StateAction::SoundAlarm],
        exit: &[],
    },
    State {
        tag: Tag::Maintenance,
        entry: &[StateAction::MaintenanceOn],
        exit: &[StateAction::MaintenanceOff],
    },
];

static EDGES: &[Edge<Door>] = &[
    Edge {
        id: "UNLOCK",
        from: Source::These(&[Tag::Locked]),
        when: Kind::EnterCode,
        check: chart::check!(CodeCorrect),
        unknown: OnUnknown::Deny,
        // Reads the digits out of `EnterCode`, so it belongs to this edge.
        run: &[Action::Unlock],
        goto: Goto::To(Tag::Unlocked),
    },
    Edge {
        id: "WRONG_CODE",
        from: Source::These(&[Tag::Locked]),
        when: Kind::EnterCode,
        check: chart::check!(!CodeCorrect && !AttemptsExceeded),
        unknown: OnUnknown::Deny,
        run: &[Action::Beep, Action::IncrementAttempts],
        goto: Goto::Internal,
    },
    Edge {
        id: "TRIGGER_ALARM",
        from: Source::These(&[Tag::Locked]),
        when: Kind::EnterCode,
        check: chart::check!(!CodeCorrect && AttemptsExceeded),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Alarm),
    },
    Edge {
        id: "RELOCK",
        from: Source::These(&[Tag::Unlocked]),
        when: Kind::Timeout,
        check: chart::check!(),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Locked),
    },
    Edge {
        id: "ALARM_RESET",
        from: Source::These(&[Tag::Alarm]),
        when: Kind::Reset,
        check: chart::check!(),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Locked),
    },
    Edge {
        id: "ENTER_MAINTENANCE",
        from: Source::These(&[Tag::Locked]),
        when: Kind::MaintenanceToggle,
        check: chart::check!(),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Maintenance),
    },
    Edge {
        id: "EXIT_MAINTENANCE",
        from: Source::These(&[Tag::Maintenance]),
        when: Kind::MaintenanceToggle,
        check: chart::check!(),
        unknown: OnUnknown::Deny,
        run: &[],
        goto: Goto::To(Tag::Locked),
    },
];

static IGNORES: &[Ignore<Door>] = &[
    Ignore {
        from: Source::These(&[Tag::Locked, Tag::Alarm, Tag::Maintenance]),
        when: &[Kind::Timeout],
        why: "the timeout only drives the automatic relock from Unlocked",
    },
    Ignore {
        from: Source::AnyExcept(&[Tag::Alarm]),
        when: &[Kind::Reset],
        why: "Reset clears the alarm, so it is only meaningful in Alarm",
    },
    Ignore {
        from: Source::These(&[Tag::Unlocked, Tag::Alarm, Tag::Maintenance]),
        when: &[Kind::EnterCode],
        why: "a code is entered to unlock, so it is only accepted in Locked",
    },
    Ignore {
        from: Source::These(&[Tag::Unlocked, Tag::Alarm]),
        when: &[Kind::MaintenanceToggle],
        why: "maintenance is toggled only between Locked and Maintenance",
    },
];

fn main() {
    let mut world = Env {
        correct_code: 1234,
        attempts: 0,
        max_attempts: 2,
        unlock_code: 0,
    };
    // A machine resumes: this tag stands in for what a real controller would
    // read back from the lock, and `Locked`'s entry does not run here.
    let mut m = Machine::new(Tag::Locked, STATES, EDGES, IGNORES);

    let steps: &[(&str, Event)] = &[
        ("wrong code, 1st", Event::EnterCode(9999)),
        ("wrong code, 2nd", Event::EnterCode(8888)),
        ("wrong code, 3rd -> alarm", Event::EnterCode(7777)),
        ("operator reset", Event::Reset),
        ("correct code", Event::EnterCode(1234)),
        ("timeout -> relock", Event::Timeout),
        ("enter maintenance", Event::MaintenanceToggle),
        ("leave maintenance", Event::MaintenanceToggle),
        // ResetAttempts ran on entry to Locked, so this counts from 1 again.
        ("wrong code (counter was cleared)", Event::EnterCode(6666)),
    ];

    println!("state = {:?}", m.tag());
    for (desc, ev) in steps {
        println!("dispatch: {desc} ({ev:?})");
        if let Some(taken) = m.dispatch(ev, &mut world) {
            println!("  edge = {}, state = {:?}", taken.edge, m.tag());
        } else {
            println!("  (ignored)");
        }
    }

    let diagram = render::to_mermaid::<Door>(Tag::Locked, EDGES, STATES);
    let md = format!("# Door lock FSM\n\n```mermaid\n{diagram}```\n");
    std::fs::write("examples/door_lock/door_lock.md", &md)
        .expect("failed to write examples/door_lock/door_lock.md");
    println!("\nmermaid diagram written to examples/door_lock/door_lock.md");

    // A defect fails the run rather than scrolling past in the output.
    let coverage = verify::coverage::<Door>(Tag::Locked, EDGES, IGNORES);
    assert!(coverage.is_clean(), "{coverage:?}");
    println!("coverage: clean");
}
